### ISSUE TITLE
Close open mongodb connections

### ISSUE THREAD

**Issue by philiiiiiipp** [HanOostdijk/matlab_mongodb#1]
Hey, good work! I think you should close the mongodb connections at the end of each script though.

`m.close()`

Running your scripts on my mac seem to result in lots of open connections and ultimately mongodb rejecting new ones.

**Comment by HanOostdijk** [comment]
philiiiiiipp,

you are quite right. Thanks for your suggestion: I have included the `close` in the scripts.

Thanks, Han
